#!/bin/bash

set -e
set -o pipefail

config_keepalived() {
  if ! compgen -A variable | grep -q -E "KEEPALIVED_VIRTUAL_IPADDRESS_[0-9]{1,3}"; then
    echo "[$(date)][KEEPALIVED] No KEEPALIVED_VIRTUAL_IPADDRESS_ varibles detected."
    return 1
  fi

  KEEPALIVED_STATE=${KEEPALIVED_STATE:-MASTER}

  if [[ "${KEEPALIVED_STATE^^}" == "MASTER" ]]; then
    KEEPALIVED_PRIORITY=${KEEPALIVED_PRIORITY:-200}
  elif [[ "${KEEPALIVED_STATE^^}" == "BACKUP" ]]; then
    KEEPALIVED_PRIORITY=${KEEPALIVED_PRIORITY:-100}
  fi

  KEEPALIVED_INTERFACE=${KEEPALIVED_INTERFACE:-eth0}
  KEEPALIVED_VIRTUAL_ROUTER_ID=${KEEPALIVED_VIRTUAL_ROUTER_ID:-51}
  KEEPALIVED_ADVERT_INT=${KEEPALIVED_ADVERT_INT:-1}
  KEEPALIVED_AUTH_PASS=${KEEPALIVED_AUTH_PASS:-"pwd$KEEPALIVED_VIRTUAL_ROUTER_ID"}

  {
    echo "vrrp_instance MAIN {"
    echo "  state $KEEPALIVED_STATE"
    echo "  interface $KEEPALIVED_INTERFACE"
    echo "  virtual_router_id $KEEPALIVED_VIRTUAL_ROUTER_ID"
    echo "  priority $KEEPALIVED_PRIORITY"
    echo "  advert_int $KEEPALIVED_ADVERT_INT"
    echo "  unicast_src_ip $KEEPALIVED_UNICAST_SRC_IP"
    echo '  unicast_peer {'
  } >> "$KEEPALIVED_CONF"
  
  for peer in $(compgen -A variable | grep -E "KEEPALIVED_UNICAST_PEER_[0-9]{1,3}"); do
    echo "    ${!peer}" >> "$KEEPALIVED_CONF"
  done
  
  {
    echo '  }'
    echo "  authentication {"
    echo "    auth_type PASS"
    echo "    auth_pass $KEEPALIVED_AUTH_PASS"
    echo "  }"
    echo "  virtual_ipaddress {"
  }  >> "$KEEPALIVED_CONF"

  for vip in $(compgen -A variable | grep -E "KEEPALIVED_VIRTUAL_IPADDRESS_[0-9]{1,3}"); do
    echo "    ${!vip}" >> "$KEEPALIVED_CONF"
  done
  echo "  }" >> "$KEEPALIVED_CONF"

  if compgen -A variable | grep -q -E "KEEPALIVED_TRACK_INTERFACE_[0-9]{1,3}"; then
    echo "  track_interface {" >> "$KEEPALIVED_CONF"
    for interface in $(compgen -A variable | grep -E "KEEPALIVED_TRACK_INTERFACE_[0-9]{1,3}"); do
      echo "    ${!interface}" >> "$KEEPALIVED_CONF"
    done
    echo "  }" >> "$KEEPALIVED_CONF"
  else
    {
      echo "  track_interface {"
      echo "    $KEEPALIVED_INTERFACE"
      echo "}"
    } >> "$KEEPALIVED_CONF"
  fi
  echo "}" >> "$KEEPALIVED_CONF"
  return 0
}

init_vars() {
  KEEPALIVED_AUTOCONF=${KEEPALIVED_AUTOCONF:-true}
  KEEPALIVED_DEBUG=${KEEPALIVED_DEBUG:-false}
  KEEPALIVED_CONF=${KEEPALIVED_CONF:-/etc/keepalived/keepalived.conf}
  KEEPALIVED_VAR_RUN=${KEEPALIVED_VAR_RUN:-/var/run/keepalived}
  if [[ ${KEEPALIVED_DEBUG,,} == "true" ]]; then
    local kd_cmd="/usr/sbin/keepalived -n -l -D -f $KEEPALIVED_CONF"
  else
    local kd_cmd="/usr/sbin/keepalived -n -l -f $KEEPALIVED_CONF"
  fi
  KEEPALIVED_CMD=${KEEPALIVED_CMD:-"$kd_cmd"}
}

main() {
  init_vars
  if [[ ${KEEPALIVED_AUTOCONF,,} == "true" ]]; then
    config_keepalived
  fi
  rm -fr "$KEEPALIVED_VAR_RUN"
  exec $KEEPALIVED_CMD
}

main