#!/bin/bash
set -m

OPENSIPS_S_MEMORY=${OPENSIPS_S_MEMORY:-1024}
OPENSIPS_P_MEMORY=${OPENSIPS_P_MEMORY:-1024}
exec /usr/sbin/opensips -f ${OPENSIPS_CFG} -P /var/run/opensips.pid -D -d 4 -m $OPENSIPS_S_MEMORY -M $OPENSIPS_P_MEMORY 