#!/bin/bash

set -e
set -o pipefail

if [ -z $HEP_SERVER ]; then
  echo "[$(date '+%Y-%m-%d %H:%M')] [ERROR] The HEP_SERVER variable wasn't set"
  return 1
else
  if [ -z $HEP_PORT ]; then
  echo "[$(date '+%Y-%m-%d %H:%M')] [WARN] The HEP_PORT variable wasn't set. Use default: 9060" 
  HEP_PORT=9060
  exec /usr/local/bin/heplify -hs ${HEP_SERVER}:${HEP_PORT}
fi